JCN 399 add id validation
janis-commerce/model pull request #21
Opened 2022-05-23 17:27 UTC by calandrajose

[Historia](https://fizzmod.atlassian.net/browse/JCN-399)
[Subtarea](https://fizzmod.atlassian.net/browse/JCN-399)

Descripción del requerimiento
Se necesita que el package [GitHub - janis-commerce/model](https://github.com/janis-commerce/model) tenga un getter idStruct que sea un “pasamanos” del getter del mismo nombre del driver de la base de datos.  Ese desarrollo se encuentra [acá](https://fizzmod.atlassian.net/browse/JCN-398)

2022-05-23 19:46 UTC, guillecipri approved these changes

2022-05-25 12:45 UTC, juanhapes requested changes

2022-05-25 12:45 UTC, juanhapes commented on package.json
> +    "@janiscommerce/superstruct": "^1.2.0",
Sumaste el package en `dependencies`, pero debería estar en `devDependencies` porque solo lo usas en los tests

2022-05-25 12:45 UTC, juanhapes commented on tests/model.js
> +				await myModel.getIdStruct('123');
No entiendo.... el `getIdStrutct()` no supone devolver el `struct`?

No se debería usar así `(await myModel.getIdStruct())('123');`? 🤔

2022-05-26 18:17 UTC, merged