add filters to getTotals
janis-commerce/model pull request #24
Opened 2023-08-30 16:23 UTC by parodimatias

### Link de la historia de usuario
https://janiscommerce.atlassian.net/browse/JCN-441

### Link de la/s sub-tareas
https://janiscommerce.atlassian.net/browse/JCN-446

### Descripción del requerimiento

Se necesita actualizar el package de [Model](https://github.com/janis-commerce/model/tree/master) para que el método getTotals pueda recibir un parametro de filters y a su vez este campo se lo pasé al driver encargado de hacer la query a la base de datos.

Esto va a servir para que el getTotals sepa calcular los totales segun filtros sin usarse el get con anterioridad

### Descripción de la solución

En model/lib/model/js modificar el metodo getTotals: incluir el param filter y pasarselo a db.getTotals(this, filter). 
Se debe en paralelo actualizar el metodo en JCN-442: Agregar filtros para getTotals en Mongodb

 
### Como probarlo

Ver https://github.com/janis-commerce/api-list/pull/18

2023-09-04 19:39 UTC, Alejandro-Gonzalez requested changes

2023-09-04 19:39 UTC, Alejandro-Gonzalez commented on tests/model.js
> +				await myCoreModel.getTotals({});
@parodimatias acá podemos meter un filtro de ejemplo y no solo el objeto

2023-09-05 18:27 UTC, gastonpereyra commented
@parodimatias Falta Actualizar el Readme

2023-09-05 18:32 UTC, Alejandro-Gonzalez approved these changes

2023-09-06 19:49 UTC, gastonpereyra approved these changes

2023-10-06 18:33 UTC, merged