apply changes
janis-commerce/model pull request #26
Opened 2024-04-23 20:29 UTC by calandrajose

Link de la tarea

Epica: https://janiscommerce.atlassian.net/browse/JCN-480

Subtarea: https://janiscommerce.atlassian.net/browse/JCN-483

### Descripción del requerimiento
Actualmente nuestros paquetes de Mongo y Model no permiten realizar múltiples operaciones de actualización en una misma query a menos que exista un indice único (`multiSave`)

En este caso, en la tarea https://janiscommerce.atlassian.net/browse/JHUB-38   surge la necesidad de actualizar todos los skus de múltiples productos, lo cual hoy solo es posible de la siguiente manera:

- obteniendo todos los registros
- modificandolos desde codigo
- guardando con un multiSave

Esta misma operación podría hacerse con una sola query que contenga algo similar a esto

```
[{
	updateMany: {
		filter: { product: '123' },
		update: {
			$set: {
				brand: product1.brand
			}
		}
	}
},
{
	updateMany: {
		filter: { product: '456' },
		update: {
			$set: {
				brand: product2.brand,
				description: product2.description
			}
		}
	}
}]
```

## Solucion

Para permitir este tipo de operaciones se sumo en https://www.npmjs.com/package/@janiscommerce/mongodb  el nuevo método `multiUpdate` el cual recibirá los parámetros `model` y `operations`. Este ultimo parámetro sera el que se ejecutara con un bulkwrite

### Descripción de la solución | Análisis Funcional
- Se agrego el nuevo método `multiUpdate` para que llame a ese mismo metodo del driver de DB

### ¿Cómo se puede probar?
Dejo pruebas realizadas en local en playground:  https://www.loom.com/share/ea24653ff8bb48899bd385439b92ca21?sid=99b91e30-3ce3-47dd-96c2-2d672f7f420a

### CHANGELOG

```
### Changed
- Add *multiUpdate* method to update multiple documents with different filters and values.
```

2024-04-23 22:30 UTC, Alejandro-Gonzalez requested changes

2024-04-23 22:30 UTC, Alejandro-Gonzalez commented on tests/model.js
> +		it('Should fail if database driver multiUpdate function rejects', async () => {
@calandrajose acá faltaría un tests mas cando resuelve correctamente. Y creo que tambien hay que agregar un cambio en los tests de model-dispatch.js

2024-04-23 22:30 UTC, Alejandro-Gonzalez commented on lib/model.js
> +		await db.multiUpdate(this, operations);
@calandrajose `return db.multiUpdate(this, operations);`

2024-04-25 20:55 UTC, Alejandro-Gonzalez commented on lib/model.js
> +		operations = operations.map(operation => {
@calandrajose el addModifiedData ya te modifica el los objetos del operatios, con un forEach estarias bien

```
operations.forEach(operation => {

	if(!isObject(operation))
		throw new ModelError('Each operation to perform must be an Object', ModelError.codes.INVALID_VALUE);

	// to standardize write methods (insert(), update(), save(), multiSave(), multiUpdate())
	this.addModifiedData(operation.data);
});
```

2024-04-25 21:20 UTC, Alejandro-Gonzalez approved these changes

2024-05-07 15:15 UTC, gastonpereyra approved these changes

2024-05-09 15:56 UTC, merged